#!/bin/bash

# Define user and group
APP_USER="csye6225"
APP_GROUP="csye6225"
APP_DIR="/opt/webapp"

echo "Creating user and group..."
sudo groupadd -f $APP_GROUP
sudo id -u $APP_USER &>/dev/null || sudo useradd -m -g $APP_GROUP -s /usr/sbin/nologin $APP_USER

echo "Setting ownership and permissions for $APP_DIR..."
sudo mkdir -p "$APP_DIR"
sudo chown -R $APP_USER:$APP_GROUP "$APP_DIR"
sudo chmod -R 750 "$APP_DIR"

echo "User setup complete."
