name: Packer Status Check

on:
  pull_request:
    branches: [main]

jobs:
  packer-format-validate:
    name: packer-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Run packer fmt
        run: |
          cd packer
          packer fmt -check -diff .

      - name: Run packer validate
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_INSTANCE_TYPE: ${{ secrets.AWS_INSTANCE_TYPE }}
          SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
          SUBNET_ID: ${{ secrets.SUBNET_ID }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          SOURCE_GCP: ${{ secrets.SOURCE_GCP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DB_NAME }}
        run: |
          cd packer
          packer validate \
            -var "aws_region=$AWS_REGION" \
            -var "aws_instance_type=$AWS_INSTANCE_TYPE" \
            -var "source_ami=$SOURCE_AMI" \
            -var "subnet_id=$SUBNET_ID" \
            -var "gcp_project_id=$GCP_PROJECT_ID" \
            -var "gcp_region=$GCP_REGION" \
            -var "source_gcp=$SOURCE_GCP" \
            -var "ssh_username=$SSH_USERNAME" \
            -var "password=$PASSWORD" \
            -var "database_name=$DATABASE_NAME"
