name: CI Packer Build

on:
  push:
    branches:
      - main

env:
  PACKER_VERSION: "1.12.0"

jobs:
  integration-test:
    name: integration test
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up PostgreSQL
        run: |
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib
          sudo systemctl start postgresql

      - name: Configure PostgreSQL User and Database
        run: |
          sudo -i -u postgres psql <<EOF
          ALTER USER postgres WITH PASSWORD '${{ secrets.DB_PASSWORD }}';
          GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;
          ALTER USER postgres WITH SUPERUSER;
          CREATE DATABASE health_check_db;
          EOF

      - name: Set up Node.js using GitHub Action
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Node.js dependencies
        run: npm install

      - name: Running tests
        run: npx jest tests/HealthCheck.test.js

  build-images:
    name: Packer Build
    needs: integration-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Extract GCP Service Account Email
        run: |
          GCP_EMAIL=$(jq -r '.client_email' <<< '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}')
          echo "GCP_EMAIL=$GCP_EMAIL" >> $GITHUB_ENV

      - name: Build Application Artifact
        working-directory: .
        run: zip -r webapp.zip .

      - name: Initialize Packer
        working-directory: packer
        run: packer init .

      - name: Validate Packer Templates
        working-directory: packer
        run: packer validate .

      - name: Build AWS & GCP Images
        working-directory: packer
        run: |
          packer build \
            -var "webapp_path=$(pwd)/webapp.zip" \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "aws_instance_type=${{ secrets.AWS_INSTANCE_TYPE }}" \
            -var "source_ami=${{ secrets.SOURCE_AMI }}" \
            -var "profile=${{ secrets.PROFILE }}" \
            -var "subnet_id=${{ secrets.SUBNET_ID }}" \
            -var "ssh_username=${{ secrets.SSH_USERNAME }}" \
            -var "db_name=${{ secrets.DB_NAME }}" \
            -var "db_username=${{ secrets.DB_USER }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "db_host=${{ secrets.DB_HOST }}" \
            -var "db_port=${{ secrets.DB_PORT }}" \
            -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "gcp_region=${{ secrets.GCP_REGION }}" \
            -var "gcp_zone=${{ secrets.GCP_ZONE }}" \
            -var "machine_type=${{ secrets.MACHINE_TYPE }}" \
            -var "service_account_email=${{ env.GCP_EMAIL }}" \
            .
