name: Packer Build Workflow

on:
  push:
    branches: [main]  # Runs only when PR is merged

jobs:
  build-packer-image:
    name: packer-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup GCP CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Run Final Packer Validation Before Build
        run: |
          cd packer
          packer validate -var-file=variables.pkrvars.hcl

      - name: Build AWS and GCP Custom Images Simultaneously
        run: |
          cd packer
          packer build -var-file=variables.pkrvars.hcl